import type { Metadata } from "next";
import "./globals.css";
import { ChildrenType } from "@/types/types";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Tabseer Shop",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en">
      <body>{children}
      <Toaster />
      </body>
    
    </html>
  );
};

export default RootLayout;
